spring:
  application:
    name: sb3-graphql-h2

  datasource:
    url: jdbc:h2:mem:sb3-graphql-h2-db
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  enabled: true
  endpoint: /graphql
  mapping: graphiql