spring:
  application:
    name: sb3-graphql-h2

  datasource:
    url: jdbc:h2:mem:sb3-graphql-h2-db
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        format_sql: true

  graphql:
    graphiql:
      enabled: true